//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrail2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractDetail()
        {
            this.Schedules = new HashSet<Schedule>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> Contractid { get; set; }
        public Nullable<int> AddressInfo { get; set; }
        public string Offering { get; set; }
        public string Version { get; set; }
        public string Branch { get; set; }
    
        public virtual AddressInfo AddressInfo1 { get; set; }
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
