//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrail2.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Schedule
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This field is required to be filled")]
        public int Scheduleid { get; set; }
        public Nullable<int> ContractDetailid { get; set; }
        public Nullable<int> Trainerid { get; set; }
        public Nullable<int> Roomid { get; set; }
        [Required(ErrorMessage = "This field is required to be filled")]
        public int ScheduleCode { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        [DataType(DataType.Text)]
        public string ScheduleStatus { get; set; }
        [DataType(DataType.Text)]
        public string Remark { get; set; }
        [DataType(DataType.Text)]
        public string IsFree { get; set; }
    
        public virtual ContractDetail ContractDetail { get; set; }
        public virtual Room Room { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
