//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrail2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int id { get; set; }
        public Nullable<int> Traineeid { get; set; }
        public Nullable<int> Contractdetailid { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string ScheduleDetailStatus { get; set; }
    
        public virtual ContractDetail ContractDetail { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
